[project]
name = "postgres-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.5",
    "psycopg2>=2.9.10",
    "pydantic[email]>=2.10.1",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.32.1",
]
